version: '3.8'

networks:
  prom_monitoring:
    driver: bridge
    name: prom_monitoring    
  nano-local:
    name: nl_nano-local
    driver: bridge
    external: 'true'

volumes:
  grafana_data: {}
  prometheus_data: {}

services:
      
  pushgateway:
    container_name: nl_pushgateway
    image: prom/pushgateway:latest
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - prom_monitoring
      - nano-local
    ports:
      - 9091:9091


  prometheus:
    container_name: nl_prometheus
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # tmpfs: /prometheus:uid=99
    command:
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    expose:
      - 9090
    networks:
      - prom_monitoring
    ports:
      - 9090:9090


  grafana:
    # 8.3.3 - terrible dashboard graph flashing
    container_name: nl_grafana
    image: grafana/grafana:8.3.2
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    # env_file:
      # - ./grafana/config.monitoring
    networks:
      - prom_monitoring
