version: '3.8'

networks:
  nano-beta:
    external:
      name: ${NANO_NODE_DOCKER_NETWORK}
    
services:
  nano-prom-exporter:
    container_name: nano-prom-exporter
    build: .
    restart: unless-stopped
    environment:
      - NANO_PROM_DEBUG=${NANO_PROM_DEBUG}
    command: --rpchost ${RPC_HOST:-host.docker.internal} --rpc_port ${RPC_PORT:-7076} --push_gateway https://prom-exporter.bnano.info
    networks:
      - nano-beta
#    profiles:
#      - exporter
