{
 "title": "pwo Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(nano_block_count, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nano_block_count, instance)"
    }
   },
   {
    "name": "stats_type",
    "label": "Stats Counters",
    "query": {
     "query": "label_values(nano_stats_counters,type)"
    }
   },
   {
    "name": "stats_detail",
    "label": "Stats Details",
    "query": {
     "query": "label_values(nano_stats_counters,detail)"
    }
   },
   {
    "name": "stats_dir",
    "label": "Stats Direction",
    "query": {
     "query": "label_values(nano_stats_counters,dir)"
    }
   },
   {
    "name": "stats_objects_l1",
    "label": "Stats Objects",
    "query": {
     "query": "label_values(nano_stats_objects_count,l1)"
    }
   },
   { "name": "Blocks", "query": "cemented,count,unchecked" },
   {
    "name": "message_type",
    "label": "Message Types",
    "query": {
     "query": "label_values(nano_stats_counters{type='message'},detail)"
    }
   },
   { "name": "Rate", "query": "1s, 5s, 15s, 30s, 60s" }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Update",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - push_time_seconds{job='${Job}', instance=~'${Instance}'}",
     "legendFormat": "[ {{instance}} ]"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "nano_node_peer_count{job='${Job}', instance=~'${Instance}'}",
     "legendFormat": "[ {{instance}} ]"
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_node_online_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] online stake"
      },
      {
       "expr": "nano_node_peers_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] peer stake"
      },
      {
       "expr": "nano_node_quorum_delta{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] quorum"
      },
      {
       "expr": "nano_node_trended_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] trended stake"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  {
   "title": "Blocks/s (over ${Rate})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}[${Rate}])",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "${message_type}/s (over ${Rate})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "message_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'message',dir=~'${stats_dir}',detail='${message_type}'}[${Rate}])",
     "legendFormat": "[ {{instance}} ] {{type}} : {{detail}} : {{dir}} "
    }
   ]
  },
  {
   "title": "Object Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "[ {{instance}} ] {{l1}} : {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Counter Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}',detail=~'${stats_detail}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{type}} : {{detail}} : {{dir}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Active Elections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Elections [avg over ${Rate}[ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1='active',l2=~'normal|hinted|optimistic'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{l1}} : {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unchecked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unchecked Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type=~'unchecked'}",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    },
    {
     "title": "Unchecked/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'unchecked'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontiers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "panels": [
    {
     "title": "Froniter Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_node_frontier_count{job='${Job}', instance=~'${Instance}'}",
       "legendFormat": "[ {{instance}} ] frontiers"
      }
     ]
    },
    {
     "title": "Frontiers/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_node_frontier_count{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] frontiers"
      }
     ]
    }
   ]
  },
  {
   "title": "TX/RX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "collapsed": true,
   "panels": [
    {
     "title": "TX/RX/s (over ${Rate}) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(network_raw_tx{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] send"
      },
      {
       "expr": "rate(network_raw_rx{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] receive"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threads (avg over $__interval) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(nano_node_threads{job=~'${Job}', instance=~'${Instance}'}[$__interval])",
       "legendFormat": "[ ${Instance} ] {{name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Confirmation History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confirmation History",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nano_confirmation_history_stats{job='${Job}', instance=~'${Instance}', type='average'}",
       "legendFormat": "[{{instance}}] {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confirmation History Heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confirmation History Heatmap [ ${Instance} ]",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
     "repeat": "Instance",
     "targets": [
      {
       "expr": "avg_over_time(nano_confirmation_history_hist_bucket{job='${Job}', instance='${Instance}', type='duration'}[${Rate}])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buckets (max over $__interval) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "repeat": "Instance",
     "targets": [
      {
       "expr": "max_over_time(nano_stats_objects_count{job='${Job}',instance=~'${Instance}',l1=~'election_scheduler : priority'}[$__interval])",
       "legendFormat": "[ ${Instance} ] {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Counter Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}'}",
       "legendFormat": "[ {{instance}} ] {{type}} : {{detail}} : {{dir}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Count Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{l1}} : {{l2}} : {{l3}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_size{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "{{instance}} {{l1}}:{{l2}}:{{l3}} size"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nano_node_memory_rss{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}} rss "
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 48 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, job))",
       "legendFormat": "Job: {{job}}"
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 48 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, method))",
       "legendFormat": "Method: {{method}}"
      }
     ]
    },
    {
     "title": "Table",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "max(nano_node_peers_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_online_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_database{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'} / nano_node_volume_total{job=~'${Remote}'} * 100) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_frontier_count{job=~'${Remote}'})by (job)"
      }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version Info",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "count (nano_version_info{job='${Job}', instance=~'${Instance}'}) by (instance,build_info,network,network_identifier,node_vendor,protocol_version,rpc_version,store_vendor,store_version)",
     "legendFormat": "{{job}} {{build_info}} {{node_vendor}} {{protocol_version}} {{rpc_version}} {{store_vendor}} {{store_version}} {{network}} {{network_identifier}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Peers",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 247 },
     "targets": [
      {
       "expr": "sum(telemetry_raw_peer{job='${Job}', instance='${Instance}'}) by(job, endpoint, protocol_version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}